default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: <%= ENV['DB_URL'] %>
  database: <%= ENV['DB_NAME'] %>
test:
  <<: *default
  host: <%= ENV['DB_URL'] %>
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  host: <%= ENV['DB_URL'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
